// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Opcode = 1,
  Prefix = 2,
  Register = 3,
  Directive = 4,
  Program = 5,
  LabelDefinition = 6,
  InstructionStatement = 7,
  Immediate = 8,
  Expression = 9,
  Memory = 10,
  Relative = 11,
  Number = 12,
  DirectiveStatement = 13,
  FullString = 14,
  SymbolDefinition = 15,
  Comment = 16
