// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {isOpcode, isRegister, isDirective} from "./asmPlugin"
export const parser = Parser.deserialize({
  version: 13,
  states: "+|OQOPOOOlOPO'#CbOOOO'#Cp'#CpOtOPO'#CcOOOO'#Cd'#CdO!VOQO'#CcO!tOPO'#CcO#bOQO'#CkOOOO'#Cw'#CwO#oOPO'#CwOOOO'#Co'#CoQQOPOOOOOO,58|,58|O#POQO,59XOOOO-E6n-E6nO!VOQO,58}O#wOPO,58}OOOO'#Cq'#CqO$SOQO'#CqO$kOQO'#ChO#POQO'#CeO$|OSO'#ChO%eOQO'#CgO%vOQO'#C{OOOO,58},58}O&UOQO'#CfO&gOSO'#CfO&{OPO'#DWOOOO,59V,59VOOOO,59c,59cOOOO-E6m-E6mOOOO1G.s1G.sOOOO1G.i1G.iO!VOQO1G.iOOOO,59R,59RO'WOPO,59ROOOO-E6o-E6oO'`OSO,59SOOOO,59P,59POOOO'#Cr'#CrO'`OSO,59SO'wOQO,59SO(YOPO,59RO(bOPO'#CjO(sOQO'#CtO)eOPO,59gO)eOPO,59gO)pOSO,59QO)pOSO,59QO#POQO,59QO*UOQO'#CuO*fOPO,59rOOOO7+$T7+$TO*qOWO'#CsO+POPO1G.mOOOO1G.m1G.mO+XOSO1G.nO'wOQO1G.nOOOO-E6p-E6pOOOO1G.n1G.nO+POPO1G.mOOOO,59U,59UO+pOPO,59UO,OOQO,59`OOOO-E6r-E6rO,^OPO1G/RO,iOSO1G.lO#POQO1G.lOOOO1G.l1G.lOOOO,59a,59aOOOO-E6s-E6sOOOO,59_,59_OOOO-E6q-E6qOOOO7+$X7+$XO'wOQO7+$YOOOO7+$Y7+$YO,}OPO7+$XOOOO1G.p1G.pOOOO1G.z1G.zO#POQO7+$WOOOO7+$W7+$WOOOO<<Gt<<GtOOOO<<Gs<<GsOOOO<<Gr<<Gr",
  stateData: "-V~OPTOQQOSVObXOlPOnSO|VP}VP~Om[O{]O~OP_OQQOnSO|VX}VX~ORgOleOpdOqaOrbOseOteO|oP}oP~OP_O|VX}VX~OljOqaOraOsjOtjO~O`kO|zP}zP~P#PO|mO}mO~OPqO|Va}Va~ORsOurOleXqeXreXseXteX~OluOqaOraOsuOtuO~OuwOvyOr[Xw[Xx[X|[X}[X~OrzOwZXxZX|ZX}ZX~Ow|Ox{O|oX}oX~Ol!POqaOraOs!POt!PO~OuwOv!ROwYX|YX}YXxYX~Ow!SO|zX}zX~Ou!XOw!VO~OuwOv!ZOr[aw[ax[a|[a}[a~OleOqaOraOseOteO~OR!^Ou!XO~OR!`Oy!_Ow^X|^X}^X~OR!aOleOpdOqaOrbOseOteOwhX|hX}hX~Ow|O|oa}oa~OuwOv!eOwYa|Ya}YaxYa~O`!gOwiX|iX}iX~P#POw!SO|za}za~OR!iO]!iOugXwgX~Ou!kOw!VO~OuwOv!lOr[iw[ix[i|[i}[i~Oy!oOw^a|^a}^a~Ox{Owha|ha}ha~Ow|O|oi}oi~OuwOv!qOwYi|Yi}YixYi~Ou!tOw!VO~O",
  goto: "%d{PPPPPP|!Q!U!]!e!]!zP#Z!QP!QP#a#g#n$U$h$r$|P%SPPP%WPPPPPPPPPP%aTWOZTXOZSUOZR`RUgT_qR!a|QkVQo]QvdQ!f!RQ!g!SQ!r!eR!u!qWfT_q|Q!]yQ!m!ZR!s!lQ!OgR!p!aQZORnZSROZR^R^cT_qy|!Z!l^iV]d!R!S!e!qTtciQxeQ!QjQ!YuW![x!Q!Y!dR!d!PQ!WsS!j!W!nR!n!^Q}gS!b}!cR!c!OQ!TkR!h!TTYOZQhTQp_R!UqRlV",
  nodeNames: "⚠ Opcode Prefix Register Directive Program LabelDefinition InstructionStatement VEXRound Immediate Expression Memory Relative Number VEXMask DirectiveStatement FullString SymbolDefinition Comment",
  maxTerm: 47,
  skippedNodes: [0],
  repeatNodeCount: 7,
  tokenData: ",t~RoYZ#Sqr#Xrs#hst$[tu$guv$lvw&wwx'Pxy'syz'xz{#c{|'}|}(U}!O'}!O!P(Z!P!Q#c!Q!R)a!R![(q![!]*_!]!^*d!^!_*i!_!`*w!`!a+P!c!}+[#Q#R#c#R#S+[#T#o+[#o#p+m#p#q,b#q#r,j#r#s,o~#XO}~U#`PvSqQ!_!`#cS#hOvS~#mU`~OY#hZr#hrs$Ps#O#h#O#P$U#P~#h~$UO`~~$XPO~#h~$aQb~OY$[Z~$[~$lOp~_$q]vSX^%jpq%j!c!}&f#R#S&f#T#o&f#y#z%j$f$g%j#BY#BZ%j$IS$I_%j$I|$JO%j$JT$JU%j$KV$KW%j&FU&FV%jZ%m]X^%jpq%j!c!}&f#R#S&f#T#o&f#y#z%j$f$g%j#BY#BZ%j$IS$I_%j$I|$JO%j$JT$JU%j$KV$KW%j&FU&FV%jZ&kS!OZ!Q![&f!c!}&f#R#S&f#T#o&fS&|PvSvw#c~'UUt~OY'PZw'Pwx'hx#O'P#O#P'm#P~'P~'mOt~~'pPO~'P~'xOr~~'}Ou~U(UOvSqQ~(ZOw~Z(bT]WsQ!O!P(q!Q![(q!c!})O#R#S)O#T#o)OY(xQ]WsQ!O!P(q!Q![(qP)TS!PP!Q![)O!c!})O#R#S)O#T#o)OY)hR]WsQ!O!P(q!Q![(q#l#m)qY)tR!Q![)}!c!i)}#T#Z)}Y*UR]WsQ!Q![)}!c!i)}#T#Z)}~*dOm~~*iO|~S*nRvS!^!_#c!_!`#c!`!a#cT*|P{P!_!`#cS+UQvS!_!`#c!`!a#c~+aSl~!Q![+[!c!}+[#R#S+[#T#o+[V+tRxUnPO#q+}#q#r,]#r~+}P,SRnPO#q+}#q#r,]#r~+}P,bOnPS,gPvS#p#q#c~,oOy~Q,tOqQ",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Program":[0,5]},
  specialized: [{term: 28, get: (value, stack) => (isOpcode(value, stack) << 1)},{term: 46, get: (value, stack) => (isRegister(value, stack) << 1)},{term: 47, get: (value, stack) => (isDirective(value, stack) << 1)}],
  tokenPrec: 0
})
