// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {isOpcode, isRegister, isDirective} from "./asmPlugin"
export const parser = Parser.deserialize({
  version: 13,
  states: "*UOQOPOOOiOPO'#CbOOOO'#Cn'#CnOqOPO'#CcO!POQO'#CcO!nOQO'#CiOOOO'#Cu'#CuO#VOPO'#CuOOOO'#Cm'#CmQQOPOOOOOO,58|,58|O#_OQO,59VOOOO-E6l-E6lO!POQO,58}OOOO'#Co'#CoO#mOQO'#CgO#_OQO'#CdO#{OSO'#CgO$aOPO'#CfO$oOWO'#CfO$zOPO'#CxOOOO,58},58}O%VOQO'#CeO%eOSO'#CeO%vOPO'#DSOOOO,59T,59TOOOO,59a,59aOOOO-E6k-E6kOOOO1G.q1G.qOOOO1G.i1G.iOOOO-E6m-E6mO&ROSO,59ROOOO,59O,59OOOOO'#Cp'#CpO&ROSO,59RO&gOQO,59RO$oOWO,59QO&uOPO'#DQO&}OPO,59QO'SOQO'#CrO'tOPO,59dO(POSO,59PO(POSO,59PO#_OQO,59PO(bOQO'#CsO(|OPO,59nO)XOSO1G.mO&gOQO1G.mOOOO-E6n-E6nOOOO1G.m1G.mO)mOPO1G.lO)rOWO'#CqO*QOPO,59lOOOO1G.l1G.lOOOO,59^,59^OOOO-E6p-E6pO*YOSO1G.kO#_OQO1G.kOOOO1G.k1G.kOOOO,59_,59_OOOO-E6q-E6qO&gOQO7+$XOOOO7+$X7+$XOOOO7+$W7+$WOOOO,59],59]OOOO-E6o-E6oO#_OQO7+$VOOOO7+$V7+$VOOOO<<Gs<<GsOOOO<<Gq<<Gq",
  stateData: "*k~OPSOQQOSTO`VOjPOxVPyVP~OkYOwZO~OP]OQQOxVXyVX~ORdOjaOm`On^OoaOpaOscOxlPylP~O^hOjgOn^OogOpgOxvPyvP~OxjOyjO~OjgOn^OogOpgO~OjoOn^OooOpoO~OqqOrsOsZXuZXxZXyZX~OstOuYXxYXyYX~ORuO[uOqtP~OuwOxlXylX~OjyOn^OoyOpyO~OqqOr{OuXXxXXyXX~Ou|OxvXyvX~OqqOr!POsZauZaxZayZa~OjaOn^OoaOpaO~Ou!TOqtX~Oq!VO~OR!WOjaOm`On^OoaOpaOscOufXxfXyfX~OuwOxlayla~OqqOr!ZOuXaxXayXa~O^!]OjgOn^OogOpgOugXxgXygX~Ou|Oxvayva~OqqOr!_OsZiuZixZiyZi~Oq!aO~OR!bO[!bOqeXueX~Ou!TOqta~OqqOr!dOuXixXiyXi~O",
  goto: "$ywPPPPPPx|!Q!X!Q!nP|P|P!|#S#Z#p$S$Y$`P$fPP$jPPPPPPP$pP$vTUOXTVOXSdS]R!WwQhTQlZQp`Q![{Q!]|Q!e!ZR!g!dUbS]wQ!RsQ!`!PR!f!_QXORkXSROXR[R[_S]sw!P!_^fTZ`{|!Z!dTn_fQraQzgQ!OoW!Qrz!O!YR!YyQ!UuR!c!UQxdR!XxQ}hR!^}TWOXQeSRm]QvcR!StRiT",
  nodeNames: "⚠ Opcode Prefix Register Directive Program LabelDefinition InstructionStatement Immediate Expression Memory Relative Number DirectiveStatement FullString SymbolDefinition Comment",
  maxTerm: 43,
  skippedNodes: [0],
  repeatNodeCount: 7,
  tokenData: "+t~RmYZ!|qr#Rrs#bst$Utu$auv$fvw&qwx&yxy'myz'rz{#]{|'w|}(O}!O'w!O!P(T!P!Q#]!Q!R)Z!R![(k![!]*X!]!^*^!^!_*c!_!`*q!`!a*y!c!}+U#Q#R#]#R#S+U#T#o+U#p#q+g#r#s+o~#ROy~U#YPrSnQ!_!`#]S#bOrS~#gU^~OY#bZr#brs#ys#O#b#O#P$O#P~#b~$OO^~~$RPO~#b~$ZQ`~OY$UZ~$U~$fOm~^$k]rSX^%dpq%d!c!}&`#R#S&`#T#o&`#y#z%d$f$g%d#BY#BZ%d$IS$I_%d$I|$JO%d$JT$JU%d$KV$KW%d&FU&FV%dY%g]X^%dpq%d!c!}&`#R#S&`#T#o&`#y#z%d$f$g%d#BY#BZ%d$IS$I_%d$I|$JO%d$JT$JU%d$KV$KW%d&FU&FV%dY&eSzY!Q![&`!c!}&`#R#S&`#T#o&`S&vPrSvw#]~'OUp~OY&yZw&ywx'bx#O&y#O#P'g#P~&y~'gOp~~'jPO~&y~'rOs~~'wOq~U(OOrSnQ~(TOu~Z([T[WoQ!O!P(k!Q![(k!c!}(x#R#S(x#T#o(xY(rQ[WoQ!O!P(k!Q![(kP(}S{P!Q![(x!c!}(x#R#S(x#T#o(xY)bR[WoQ!O!P(k!Q![(k#l#m)kY)nR!Q![)w!c!i)w#T#Z)wY*OR[WoQ!Q![)w!c!i)w#T#Z)w~*^Ok~~*cOx~S*hRrS!^!_#]!_!`#]!`!a#]T*vPwP!_!`#]S+OQrS!_!`#]!`!a#]~+ZSj~!Q![+U!c!}+U#R#S+U#T#o+US+lPrS#p#q#]Q+tOnQ",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Program":[0,5]},
  specialized: [{term: 26, get: (value, stack) => (isOpcode(value, stack) << 1)},{term: 42, get: (value, stack) => (isRegister(value, stack) << 1)},{term: 43, get: (value, stack) => (isDirective(value, stack) << 1)}],
  tokenPrec: 0
})
