// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {isOpcode, isRegister, isDirective} from "./asmPlugin"
export const parser = Parser.deserialize({
  version: 13,
  states: "+pOQOPOOOlOPO'#CbOOOO'#Cp'#CpOtOPO'#CcOOOO'#Cd'#CdO!VOQO'#CcO!tOPO'#CcO#POQO'#CkOOOO'#Cw'#CwO#hOPO'#CwOOOO'#Co'#CoQQOPOOOOOO,58|,58|O#pOQO,59XOOOO-E6n-E6nO!VOQO,58}O$OOPO,58}OOOO'#Cq'#CqO$ZOQO'#ChO#pOQO'#CeO$iOSO'#ChO%QOQO'#CgO%cOWO'#CgO%nOQO'#C{OOOO,58},58}O%|OQO'#CfO&[OSO'#CfO&pOPO'#DXOOOO,59V,59VOOOO,59c,59cOOOO-E6m-E6mOOOO1G.s1G.sOOOO1G.i1G.iO!VOQO1G.iOOOO-E6o-E6oO&{OSO,59SOOOO,59P,59POOOO'#Cr'#CrO&{OSO,59SO'dOQO,59SO%cOWO,59RO'rOPO'#DTO'zOPO,59RO(POPO'#CjO(bOQO'#CtO)SOPO,59gO)SOPO,59gO)_OSO,59QO)_OSO,59QO#pOQO,59QO)sOQO'#CuO*_OPO,59sOOOO7+$T7+$TO*jOSO1G.nO'dOQO1G.nOOOO-E6p-E6pOOOO1G.n1G.nO+ROPO1G.mO+WOWO'#CsO+fOPO,59oOOOO1G.m1G.mOOOO,59U,59UO+nOPO,59UO+|OQO,59`OOOO-E6r-E6rO,[OPO1G/RO,gOSO1G.lO#pOQO1G.lOOOO1G.l1G.lOOOO,59a,59aOOOO-E6s-E6sO'dOQO7+$YOOOO7+$Y7+$YOOOO7+$X7+$XOOOO,59_,59_OOOO-E6q-E6qOOOO1G.p1G.pOOOO1G.z1G.zO#pOQO7+$WOOOO7+$W7+$WOOOO<<Gt<<GtOOOO<<Gr<<Gr",
  stateData: ",{~OPTOQQOSVObXOlPOnSO}VP!OVP~Om[O|]O~OP_OQQOnSO}VX!OVX~ORgOldOpcOqaOrdOsdOvfO}oP!OoP~OP_O}VX!OVX~O`kOljOqaOrjOsjO}{P!O{P~O}mO!OmO~OljOqaOrjOsjO~OPqO}Va!OVa~OlsOqaOrsOssO~OtuOuwOv[Xx[Xy[X}[X!O[X~OvxOxZXyZX}ZX!OZX~ORyO]yOtwP~Ox|Oy{O}oX!OoX~Ol!POqaOr!POs!PO~OtuOu!ROxYX}YX!OYXyYX~Ox!SO}{X!O{X~OtuOu!WOv[ax[ay[a}[a!O[a~OldOqaOrdOsdO~Ox![OtwX~Ot!^O~OR!`Oz!_Ox^X}^X!O^X~OR!aOldOpcOqaOrdOsdOvfOxhX}hX!OhX~Ox|O}oa!Ooa~OtuOu!eOxYa}Ya!OYayYa~O`!gOljOqaOrjOsjOxiX}iX!OiX~Ox!SO}{a!O{a~OtuOu!iOv[ix[iy[i}[i!O[i~Ot!kO~OR!lO]!lOtgXxgX~Ox![Otwa~Oz!nOx^a}^a!O^a~Oy{Oxha}ha!Oha~Ox|O}oi!Ooi~OtuOu!pOxYi}Yi!OYiyYi~O",
  goto: "%g|PPPPPP}!R!V!^!f!^!{P#[!RP!RP#b#h#o$V$i$o$yP%PPPP%TPPPPPPP%^PPP%dTWOZTXOZSUOZR`RUgT_qR!a|QkVQo]QtcQ!f!RQ!g!SQ!q!eR!s!pWeT_q|Q!YwQ!j!WR!r!iQ!OgR!o!aQZORnZSROZR^R^bT_qw|!W!i^iV]c!R!S!e!pTrbiQvdQ!QjQ!VsW!Xv!Q!V!dR!d!PQ!]yR!m!]Q}gS!b}!cR!c!OQ!TkR!h!TTYOZQhTQp_R!UqQzfR!ZxRlV",
  nodeNames: "⚠ Opcode Prefix Register Directive Program LabelDefinition InstructionStatement VEXRound Immediate Expression Memory Relative Number VEXMask DirectiveStatement FullString SymbolDefinition Comment",
  maxTerm: 48,
  skippedNodes: [0],
  repeatNodeCount: 7,
  tokenData: ",t~RoYZ#Sqr#Xrs#hst$[tu$guv$lvw&wwx'Pxy'syz'xz{#c{|'}|}(U}!O'}!O!P(Z!P!Q#c!Q!R)a!R![(q![!]*_!]!^*d!^!_*i!_!`*w!`!a+P!c!}+[#Q#R#c#R#S+[#T#o+[#o#p+m#p#q,b#q#r,j#r#s,o~#XO!O~U#`PuSqQ!_!`#cS#hOuS~#mU`~OY#hZr#hrs$Ps#O#h#O#P$U#P~#h~$UO`~~$XPO~#h~$aQb~OY$[Z~$[~$lOp~_$q]uSX^%jpq%j!c!}&f#R#S&f#T#o&f#y#z%j$f$g%j#BY#BZ%j$IS$I_%j$I|$JO%j$JT$JU%j$KV$KW%j&FU&FV%jZ%m]X^%jpq%j!c!}&f#R#S&f#T#o&f#y#z%j$f$g%j#BY#BZ%j$IS$I_%j$I|$JO%j$JT$JU%j$KV$KW%j&FU&FV%jZ&kS!PZ!Q![&f!c!}&f#R#S&f#T#o&fS&|PuSvw#c~'UUs~OY'PZw'Pwx'hx#O'P#O#P'm#P~'P~'mOs~~'pPO~'P~'xOv~~'}Ot~U(UOuSqQ~(ZOx~Z(bT]WrQ!O!P(q!Q![(q!c!})O#R#S)O#T#o)OY(xQ]WrQ!O!P(q!Q![(qP)TS!QP!Q![)O!c!})O#R#S)O#T#o)OY)hR]WrQ!O!P(q!Q![(q#l#m)qY)tR!Q![)}!c!i)}#T#Z)}Y*UR]WrQ!Q![)}!c!i)}#T#Z)}~*dOm~~*iO}~S*nRuS!^!_#c!_!`#c!`!a#cT*|P|P!_!`#cS+UQuS!_!`#c!`!a#c~+aSl~!Q![+[!c!}+[#R#S+[#T#o+[V+tRyUnPO#q+}#q#r,]#r~+}P,SRnPO#q+}#q#r,]#r~+}P,bOnPS,gPuS#p#q#c~,oOz~Q,tOqQ",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Program":[0,5]},
  specialized: [{term: 28, get: (value, stack) => (isOpcode(value, stack) << 1)},{term: 47, get: (value, stack) => (isRegister(value, stack) << 1)},{term: 48, get: (value, stack) => (isDirective(value, stack) << 1)}],
  tokenPrec: 0
})
