// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Opcode = 1,
  Prefix = 2,
  Register = 3,
  Directive = 4,
  Program = 5,
  InstructionStatement = 6,
  Immediate = 7,
  DirectiveStatement = 8,
  Expression = 9,
  FullString = 10,
  MacroDefinition = 11,
  LabelDefinition = 12,
  Comment = 13
